### ISSUE TITLE
Negative surface densities

### ISSUE THREAD

**Issue by segasai** [mgieles/limepy#1]
Hi,

The surface densities returned for some of the King models are negative: 

In [147]: ZZ=limepy.limepy(4.57549865751,1,project=True)
In [148]: print ZZ.Sigma[-4:]
[  7.56440098e-26  -1.20531932e-26   2.15521450e-27   0.00000000e+00]
In [149]: print ZZ.rho.min()
0.0

It is clearly not a big deal, and could be dealt outside of limepy, but it may be still worth fixing. The issue seems to be caused not by the Poisson solver, because the 3D densities are all positive. My guess is the likely cause is the projection and the usage of the interpolator there. That probably breaks the non-negativity of the projection integrand.

Cheers,
 Sergey

If it is relevant (very unlikely), Python version is 2.7, OS  RHEL6, limepy version is the latest from git.

**Comment by mgieles** [comment]
This is a numerical artefact as the result of projecting a small number of density array elements with very small values (1e-20) at the edge. Because these values are below the numerically accuracy of the Poisson solver, this is not a real issue affecting the result, and it "solved" by always reporting the absolute value of the projected density, which avoids negative results at the edge.
