### ISSUE TITLE
Mass enclosed within SPES model

### ISSUE THREAD

**Issue by webbjj** [mgieles/limepy#5]
After running the example command: s = spes(7,B=0.99,eta=0.1,nrt=2,M=1e5,rh=3,project=True), I tried to plot mass enclosed (s.mc) versus radius (s.r). However it turns out that the radius array and mass enclosed arrays are different lengths (66 and 57 respectively). I am guessing they should both be the same length?

I am guessing this is also the source of error when trying to run s._setup_phi_interpolator() The exact error is "ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 66 and the array at index 1 has size 57". Or perhaps this feature is not available in the SPES models?

**Comment by mgieles** [comment]
Both problems have been solved. 

The enclosed mass array was too short because the solution outside the tidal radius was not considered. The SPES models assume that the mass outside rt does not contribute to the mass, so the array self.mc is now simply extended with the final value at rt

For the same reason the potential interpolator did not work. The potential outside rt is assumed to be Keplerian, and is now continuously and smoothly joining the potential inside rt.

**Comment by webbjj** [comment]
Thanks Mark!
